[2025-09-06 12:36:37,702] {processor.py:153} INFO - Started process (PID=32068) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:36:37,703] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:36:37,704] {logging_mixin.py:115} INFO - [2025-09-06 12:36:37,704] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:36:37,735] {logging_mixin.py:115} INFO - [2025-09-06 12:36:37,731] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:36:37,736] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:36:37,792] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.095 seconds
[2025-09-06 12:37:21,953] {processor.py:153} INFO - Started process (PID=32196) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:37:21,955] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:37:21,956] {logging_mixin.py:115} INFO - [2025-09-06 12:37:21,956] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:37:21,969] {logging_mixin.py:115} INFO - [2025-09-06 12:37:21,966] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:37:21,970] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:37:22,001] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.059 seconds
[2025-09-06 12:37:54,579] {processor.py:153} INFO - Started process (PID=32365) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:37:54,580] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:37:54,582] {logging_mixin.py:115} INFO - [2025-09-06 12:37:54,581] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:37:54,599] {logging_mixin.py:115} INFO - [2025-09-06 12:37:54,596] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:37:54,600] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:37:54,651] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.077 seconds
[2025-09-06 12:38:29,301] {processor.py:153} INFO - Started process (PID=32513) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:38:29,302] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:38:29,303] {logging_mixin.py:115} INFO - [2025-09-06 12:38:29,303] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:38:29,317] {logging_mixin.py:115} INFO - [2025-09-06 12:38:29,315] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:38:29,317] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:38:29,353] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.059 seconds
[2025-09-06 12:39:08,383] {processor.py:153} INFO - Started process (PID=32755) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:39:08,385] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:39:08,387] {logging_mixin.py:115} INFO - [2025-09-06 12:39:08,387] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:39:08,401] {logging_mixin.py:115} INFO - [2025-09-06 12:39:08,399] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:39:08,401] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:39:08,438] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.063 seconds
[2025-09-06 12:39:43,462] {processor.py:153} INFO - Started process (PID=32931) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:39:43,464] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:39:43,465] {logging_mixin.py:115} INFO - [2025-09-06 12:39:43,465] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:39:43,474] {logging_mixin.py:115} INFO - [2025-09-06 12:39:43,473] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:39:43,474] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:39:43,506] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.049 seconds
[2025-09-06 12:40:17,807] {processor.py:153} INFO - Started process (PID=33103) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:40:17,809] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:40:17,811] {logging_mixin.py:115} INFO - [2025-09-06 12:40:17,810] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:40:17,824] {logging_mixin.py:115} INFO - [2025-09-06 12:40:17,823] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:40:17,824] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:40:17,854] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.059 seconds
[2025-09-06 12:40:54,959] {processor.py:153} INFO - Started process (PID=33193) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:40:54,961] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:40:54,962] {logging_mixin.py:115} INFO - [2025-09-06 12:40:54,961] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:40:54,971] {logging_mixin.py:115} INFO - [2025-09-06 12:40:54,970] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:40:54,971] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:40:55,009] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.054 seconds
[2025-09-06 12:41:27,563] {processor.py:153} INFO - Started process (PID=33355) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:41:27,565] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:41:27,567] {logging_mixin.py:115} INFO - [2025-09-06 12:41:27,567] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:41:27,582] {logging_mixin.py:115} INFO - [2025-09-06 12:41:27,580] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:41:27,582] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:41:27,613] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.064 seconds
[2025-09-06 12:42:01,084] {processor.py:153} INFO - Started process (PID=33493) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:42:01,086] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:42:01,087] {logging_mixin.py:115} INFO - [2025-09-06 12:42:01,086] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:42:01,098] {logging_mixin.py:115} INFO - [2025-09-06 12:42:01,097] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:42:01,100] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:42:01,134] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.054 seconds
[2025-09-06 12:42:38,910] {processor.py:153} INFO - Started process (PID=33582) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:42:38,911] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:42:38,912] {logging_mixin.py:115} INFO - [2025-09-06 12:42:38,912] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:42:38,922] {logging_mixin.py:115} INFO - [2025-09-06 12:42:38,922] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:42:38,923] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:42:38,955] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.048 seconds
[2025-09-06 12:43:18,737] {processor.py:153} INFO - Started process (PID=33723) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:43:18,739] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:43:18,740] {logging_mixin.py:115} INFO - [2025-09-06 12:43:18,740] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:43:18,757] {logging_mixin.py:115} INFO - [2025-09-06 12:43:18,755] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:43:18,757] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:43:18,804] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.073 seconds
[2025-09-06 12:43:55,741] {processor.py:153} INFO - Started process (PID=33818) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:43:55,742] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:43:55,743] {logging_mixin.py:115} INFO - [2025-09-06 12:43:55,743] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:43:55,754] {logging_mixin.py:115} INFO - [2025-09-06 12:43:55,753] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:43:55,754] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:43:55,792] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.056 seconds
[2025-09-06 12:44:25,922] {processor.py:153} INFO - Started process (PID=33917) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:44:25,923] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:44:25,924] {logging_mixin.py:115} INFO - [2025-09-06 12:44:25,924] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:44:25,938] {logging_mixin.py:115} INFO - [2025-09-06 12:44:25,936] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:44:25,938] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:44:25,972] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.055 seconds
[2025-09-06 12:45:04,063] {processor.py:153} INFO - Started process (PID=34033) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:45:04,065] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:45:04,066] {logging_mixin.py:115} INFO - [2025-09-06 12:45:04,065] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:45:04,083] {logging_mixin.py:115} INFO - [2025-09-06 12:45:04,080] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:45:04,084] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:45:04,119] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.059 seconds
[2025-09-06 12:45:38,053] {processor.py:153} INFO - Started process (PID=34172) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:45:38,055] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:45:38,056] {logging_mixin.py:115} INFO - [2025-09-06 12:45:38,056] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:45:38,070] {logging_mixin.py:115} INFO - [2025-09-06 12:45:38,069] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:45:38,070] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:45:38,108] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.060 seconds
[2025-09-06 12:46:12,356] {processor.py:153} INFO - Started process (PID=34249) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:46:12,357] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:46:12,359] {logging_mixin.py:115} INFO - [2025-09-06 12:46:12,358] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:46:12,399] {logging_mixin.py:115} INFO - [2025-09-06 12:46:12,397] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:46:12,400] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:46:12,483] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.141 seconds
[2025-09-06 12:46:49,223] {processor.py:153} INFO - Started process (PID=34329) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:46:49,227] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:46:49,229] {logging_mixin.py:115} INFO - [2025-09-06 12:46:49,229] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:46:49,251] {logging_mixin.py:115} INFO - [2025-09-06 12:46:49,250] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    from airflow.utils.dates import ds_add
ImportError: cannot import name 'ds_add' from 'airflow.utils.dates' (/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/dates.py)
[2025-09-06 12:46:49,252] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:46:49,291] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.081 seconds
[2025-09-06 12:47:23,609] {processor.py:153} INFO - Started process (PID=34468) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:47:23,611] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:47:23,612] {logging_mixin.py:115} INFO - [2025-09-06 12:47:23,612] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:47:26,393] {logging_mixin.py:115} INFO - [2025-09-06 12:47:26,391] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 40, in <module>
    tarefa_2 = PythonOperator(
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 348, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2025-09-06 12:47:26,394] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:47:26,423] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 2.819 seconds
[2025-09-06 12:48:05,200] {processor.py:153} INFO - Started process (PID=34553) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:48:05,204] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:48:05,205] {logging_mixin.py:115} INFO - [2025-09-06 12:48:05,205] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:48:06,257] {logging_mixin.py:115} INFO - [2025-09-06 12:48:06,255] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 40, in <module>
    tarefa_2 = PythonOperator(
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 348, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2025-09-06 12:48:06,257] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:48:06,286] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 1.094 seconds
[2025-09-06 12:48:47,217] {processor.py:153} INFO - Started process (PID=34659) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:48:47,220] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:48:47,221] {logging_mixin.py:115} INFO - [2025-09-06 12:48:47,221] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:48:48,020] {logging_mixin.py:115} INFO - [2025-09-06 12:48:48,018] {dagbag.py:320} ERROR - Failed to import: /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lucas/Documents/airflowalura/dags/dados_climaticos.py", line 40, in <module>
    tarefa_2 = PythonOperator(
  File "/home/lucas/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 348, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2025-09-06 12:48:48,021] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:48:48,050] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.842 seconds
[2025-09-06 12:49:29,643] {processor.py:153} INFO - Started process (PID=34756) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:49:29,644] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:49:29,645] {logging_mixin.py:115} INFO - [2025-09-06 12:49:29,645] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:49:30,203] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:49:30,299] {logging_mixin.py:115} INFO - [2025-09-06 12:49:30,299] {manager.py:508} INFO - Created Permission View: can delete on DAG:dados_climatico
[2025-09-06 12:49:30,331] {logging_mixin.py:115} INFO - [2025-09-06 12:49:30,331] {manager.py:508} INFO - Created Permission View: can edit on DAG:dados_climatico
[2025-09-06 12:49:30,365] {logging_mixin.py:115} INFO - [2025-09-06 12:49:30,365] {manager.py:508} INFO - Created Permission View: can read on DAG:dados_climatico
[2025-09-06 12:49:30,366] {logging_mixin.py:115} INFO - [2025-09-06 12:49:30,365] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:49:30,379] {logging_mixin.py:115} INFO - [2025-09-06 12:49:30,379] {dag.py:2398} INFO - Creating ORM DAG for dados_climatico
[2025-09-06 12:49:30,396] {logging_mixin.py:115} INFO - [2025-09-06 12:49:30,396] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-08-11T00:00:00+00:00, run_after=2025-08-18T00:00:00+00:00
[2025-09-06 12:49:30,454] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.815 seconds
[2025-09-06 12:50:08,056] {processor.py:153} INFO - Started process (PID=34858) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:50:08,058] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:50:08,059] {logging_mixin.py:115} INFO - [2025-09-06 12:50:08,059] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:50:08,480] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:50:08,492] {logging_mixin.py:115} INFO - [2025-09-06 12:50:08,492] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:50:08,511] {logging_mixin.py:115} INFO - [2025-09-06 12:50:08,511] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-08-11T00:00:00+00:00, run_after=2025-08-18T00:00:00+00:00
[2025-09-06 12:50:08,533] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.481 seconds
[2025-09-06 12:50:41,866] {processor.py:153} INFO - Started process (PID=34944) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:50:41,867] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:50:41,869] {logging_mixin.py:115} INFO - [2025-09-06 12:50:41,868] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:50:42,280] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:50:42,292] {logging_mixin.py:115} INFO - [2025-09-06 12:50:42,292] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:50:42,311] {logging_mixin.py:115} INFO - [2025-09-06 12:50:42,311] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-08-11T00:00:00+00:00, run_after=2025-08-18T00:00:00+00:00
[2025-09-06 12:50:42,337] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.484 seconds
[2025-09-06 12:51:18,799] {processor.py:153} INFO - Started process (PID=35035) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:51:18,800] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:51:18,802] {logging_mixin.py:115} INFO - [2025-09-06 12:51:18,801] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:51:19,214] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:51:19,227] {logging_mixin.py:115} INFO - [2025-09-06 12:51:19,227] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:51:19,246] {logging_mixin.py:115} INFO - [2025-09-06 12:51:19,246] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-08-11T00:00:00+00:00, run_after=2025-08-18T00:00:00+00:00
[2025-09-06 12:51:19,269] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.475 seconds
[2025-09-06 12:51:55,219] {processor.py:153} INFO - Started process (PID=35148) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:51:55,222] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:51:55,224] {logging_mixin.py:115} INFO - [2025-09-06 12:51:55,224] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:51:55,728] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:51:55,744] {logging_mixin.py:115} INFO - [2025-09-06 12:51:55,744] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:51:55,766] {logging_mixin.py:115} INFO - [2025-09-06 12:51:55,766] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:51:55,798] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.589 seconds
[2025-09-06 12:52:33,671] {processor.py:153} INFO - Started process (PID=35249) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:52:33,673] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:52:33,674] {logging_mixin.py:115} INFO - [2025-09-06 12:52:33,674] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:52:34,115] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:52:34,129] {logging_mixin.py:115} INFO - [2025-09-06 12:52:34,129] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:52:34,150] {logging_mixin.py:115} INFO - [2025-09-06 12:52:34,150] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:52:34,173] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.511 seconds
[2025-09-06 12:53:05,411] {processor.py:153} INFO - Started process (PID=35325) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:53:05,414] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:53:05,418] {logging_mixin.py:115} INFO - [2025-09-06 12:53:05,417] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:53:06,081] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:53:06,101] {logging_mixin.py:115} INFO - [2025-09-06 12:53:06,101] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:53:06,133] {logging_mixin.py:115} INFO - [2025-09-06 12:53:06,132] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:53:06,167] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.777 seconds
[2025-09-06 12:53:40,678] {processor.py:153} INFO - Started process (PID=35407) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:53:40,681] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:53:40,683] {logging_mixin.py:115} INFO - [2025-09-06 12:53:40,683] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:53:41,093] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:53:41,106] {logging_mixin.py:115} INFO - [2025-09-06 12:53:41,106] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:53:41,126] {logging_mixin.py:115} INFO - [2025-09-06 12:53:41,126] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:53:41,148] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.482 seconds
[2025-09-06 12:54:16,040] {processor.py:153} INFO - Started process (PID=35487) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:54:16,041] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:54:16,042] {logging_mixin.py:115} INFO - [2025-09-06 12:54:16,042] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:54:16,475] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:54:16,490] {logging_mixin.py:115} INFO - [2025-09-06 12:54:16,489] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:54:16,511] {logging_mixin.py:115} INFO - [2025-09-06 12:54:16,510] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:54:16,536] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.500 seconds
[2025-09-06 12:54:55,875] {processor.py:153} INFO - Started process (PID=35596) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:54:55,876] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:54:55,877] {logging_mixin.py:115} INFO - [2025-09-06 12:54:55,877] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:54:56,359] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:54:56,374] {logging_mixin.py:115} INFO - [2025-09-06 12:54:56,374] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:54:56,396] {logging_mixin.py:115} INFO - [2025-09-06 12:54:56,396] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:54:56,419] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.549 seconds
[2025-09-06 12:55:31,325] {processor.py:153} INFO - Started process (PID=35688) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:55:31,326] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:55:31,327] {logging_mixin.py:115} INFO - [2025-09-06 12:55:31,327] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:55:32,258] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:55:32,286] {logging_mixin.py:115} INFO - [2025-09-06 12:55:32,285] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:55:32,326] {logging_mixin.py:115} INFO - [2025-09-06 12:55:32,325] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:55:32,376] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 1.055 seconds
[2025-09-06 12:56:08,812] {processor.py:153} INFO - Started process (PID=35773) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:56:08,814] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:56:08,817] {logging_mixin.py:115} INFO - [2025-09-06 12:56:08,816] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:56:09,407] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:56:09,422] {logging_mixin.py:115} INFO - [2025-09-06 12:56:09,421] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:56:09,441] {logging_mixin.py:115} INFO - [2025-09-06 12:56:09,441] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:56:09,475] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.677 seconds
[2025-09-06 12:56:46,052] {processor.py:153} INFO - Started process (PID=35866) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:56:46,054] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:56:46,055] {logging_mixin.py:115} INFO - [2025-09-06 12:56:46,055] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:56:46,818] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:56:46,832] {logging_mixin.py:115} INFO - [2025-09-06 12:56:46,832] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:56:46,852] {logging_mixin.py:115} INFO - [2025-09-06 12:56:46,851] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:56:46,874] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.828 seconds
[2025-09-06 12:57:17,437] {processor.py:153} INFO - Started process (PID=35936) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:57:17,440] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:57:17,441] {logging_mixin.py:115} INFO - [2025-09-06 12:57:17,441] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:57:18,255] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:57:18,270] {logging_mixin.py:115} INFO - [2025-09-06 12:57:18,269] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:57:18,297] {logging_mixin.py:115} INFO - [2025-09-06 12:57:18,297] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:57:18,325] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.899 seconds
[2025-09-06 12:57:50,875] {processor.py:153} INFO - Started process (PID=36019) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:57:50,876] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:57:50,878] {logging_mixin.py:115} INFO - [2025-09-06 12:57:50,878] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:57:51,395] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:57:51,416] {logging_mixin.py:115} INFO - [2025-09-06 12:57:51,416] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:57:51,444] {logging_mixin.py:115} INFO - [2025-09-06 12:57:51,444] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:57:51,472] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.606 seconds
[2025-09-06 12:58:23,671] {processor.py:153} INFO - Started process (PID=36092) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:58:23,673] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:58:23,675] {logging_mixin.py:115} INFO - [2025-09-06 12:58:23,674] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:58:24,126] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:58:24,138] {logging_mixin.py:115} INFO - [2025-09-06 12:58:24,138] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:58:24,157] {logging_mixin.py:115} INFO - [2025-09-06 12:58:24,157] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:58:24,186] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.523 seconds
[2025-09-06 12:59:00,051] {processor.py:153} INFO - Started process (PID=36178) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:59:00,052] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:59:00,053] {logging_mixin.py:115} INFO - [2025-09-06 12:59:00,052] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:59:00,681] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:59:00,696] {logging_mixin.py:115} INFO - [2025-09-06 12:59:00,695] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:59:00,727] {logging_mixin.py:115} INFO - [2025-09-06 12:59:00,727] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 12:59:00,752] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.705 seconds
[2025-09-06 12:59:41,985] {processor.py:153} INFO - Started process (PID=36291) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:59:41,988] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 12:59:41,990] {logging_mixin.py:115} INFO - [2025-09-06 12:59:41,990] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:59:43,562] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 12:59:43,647] {logging_mixin.py:115} INFO - [2025-09-06 12:59:43,646] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 12:59:43,662] {logging_mixin.py:115} INFO - [2025-09-06 12:59:43,662] {dag.py:2398} INFO - Creating ORM DAG for dados_climatico
[2025-09-06 12:59:43,696] {logging_mixin.py:115} INFO - [2025-09-06 12:59:43,695] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-08-11T00:00:00+00:00, run_after=2025-08-18T00:00:00+00:00
[2025-09-06 12:59:43,756] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 1.777 seconds
[2025-09-06 13:00:15,278] {processor.py:153} INFO - Started process (PID=36367) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:00:15,279] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:00:15,280] {logging_mixin.py:115} INFO - [2025-09-06 13:00:15,280] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:00:15,863] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:00:15,876] {logging_mixin.py:115} INFO - [2025-09-06 13:00:15,876] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:00:15,895] {logging_mixin.py:115} INFO - [2025-09-06 13:00:15,895] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-08-11T00:00:00+00:00, run_after=2025-08-18T00:00:00+00:00
[2025-09-06 13:00:15,917] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.647 seconds
[2025-09-06 13:00:46,337] {processor.py:153} INFO - Started process (PID=36443) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:00:46,339] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:00:46,341] {logging_mixin.py:115} INFO - [2025-09-06 13:00:46,341] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:00:46,749] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:00:46,762] {logging_mixin.py:115} INFO - [2025-09-06 13:00:46,761] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:00:46,780] {logging_mixin.py:115} INFO - [2025-09-06 13:00:46,780] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-08-11T00:00:00+00:00, run_after=2025-08-18T00:00:00+00:00
[2025-09-06 13:00:46,803] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.478 seconds
[2025-09-06 13:01:19,803] {processor.py:153} INFO - Started process (PID=36528) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:01:19,804] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:01:19,805] {logging_mixin.py:115} INFO - [2025-09-06 13:01:19,805] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:01:20,242] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:01:20,254] {logging_mixin.py:115} INFO - [2025-09-06 13:01:20,254] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:01:20,273] {logging_mixin.py:115} INFO - [2025-09-06 13:01:20,273] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-08-11T00:00:00+00:00, run_after=2025-08-18T00:00:00+00:00
[2025-09-06 13:01:20,296] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.496 seconds
[2025-09-06 13:01:54,487] {processor.py:153} INFO - Started process (PID=36612) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:01:54,491] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:01:54,492] {logging_mixin.py:115} INFO - [2025-09-06 13:01:54,492] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:01:55,143] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:01:55,162] {logging_mixin.py:115} INFO - [2025-09-06 13:01:55,161] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:01:55,195] {logging_mixin.py:115} INFO - [2025-09-06 13:01:55,195] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-08-11T00:00:00+00:00, run_after=2025-08-18T00:00:00+00:00
[2025-09-06 13:01:55,232] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.753 seconds
[2025-09-06 13:02:49,937] {processor.py:153} INFO - Started process (PID=36762) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:02:49,938] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:02:49,939] {logging_mixin.py:115} INFO - [2025-09-06 13:02:49,938] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:02:50,365] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:02:50,378] {logging_mixin.py:115} INFO - [2025-09-06 13:02:50,377] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:02:50,396] {logging_mixin.py:115} INFO - [2025-09-06 13:02:50,396] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:02:50,418] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.485 seconds
[2025-09-06 13:03:24,391] {processor.py:153} INFO - Started process (PID=36848) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:03:24,394] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:03:24,397] {logging_mixin.py:115} INFO - [2025-09-06 13:03:24,396] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:03:24,808] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:03:24,820] {logging_mixin.py:115} INFO - [2025-09-06 13:03:24,820] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:03:24,839] {logging_mixin.py:115} INFO - [2025-09-06 13:03:24,839] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:03:24,865] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.486 seconds
[2025-09-06 13:04:00,023] {processor.py:153} INFO - Started process (PID=36933) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:04:00,024] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:04:00,025] {logging_mixin.py:115} INFO - [2025-09-06 13:04:00,025] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:04:00,449] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:04:00,462] {logging_mixin.py:115} INFO - [2025-09-06 13:04:00,462] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:04:00,481] {logging_mixin.py:115} INFO - [2025-09-06 13:04:00,480] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:04:00,502] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.483 seconds
[2025-09-06 13:04:35,762] {processor.py:153} INFO - Started process (PID=37051) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:04:35,765] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:04:35,768] {logging_mixin.py:115} INFO - [2025-09-06 13:04:35,768] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:04:36,181] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:04:36,193] {logging_mixin.py:115} INFO - [2025-09-06 13:04:36,193] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:04:36,212] {logging_mixin.py:115} INFO - [2025-09-06 13:04:36,212] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:04:36,235] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.484 seconds
[2025-09-06 13:05:11,340] {processor.py:153} INFO - Started process (PID=37141) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:05:11,341] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:05:11,342] {logging_mixin.py:115} INFO - [2025-09-06 13:05:11,342] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:05:11,757] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:05:11,770] {logging_mixin.py:115} INFO - [2025-09-06 13:05:11,770] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:05:11,789] {logging_mixin.py:115} INFO - [2025-09-06 13:05:11,789] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:05:11,812] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.476 seconds
[2025-09-06 13:05:44,482] {processor.py:153} INFO - Started process (PID=37219) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:05:44,483] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:05:44,484] {logging_mixin.py:115} INFO - [2025-09-06 13:05:44,484] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:05:44,898] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:05:44,911] {logging_mixin.py:115} INFO - [2025-09-06 13:05:44,911] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:05:44,932] {logging_mixin.py:115} INFO - [2025-09-06 13:05:44,931] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:05:44,953] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.475 seconds
[2025-09-06 13:06:15,678] {processor.py:153} INFO - Started process (PID=37287) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:06:15,679] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:06:15,679] {logging_mixin.py:115} INFO - [2025-09-06 13:06:15,679] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:06:16,093] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:06:16,105] {logging_mixin.py:115} INFO - [2025-09-06 13:06:16,105] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:06:16,124] {logging_mixin.py:115} INFO - [2025-09-06 13:06:16,124] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:06:16,146] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.474 seconds
[2025-09-06 13:06:52,147] {processor.py:153} INFO - Started process (PID=37383) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:06:52,148] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:06:52,149] {logging_mixin.py:115} INFO - [2025-09-06 13:06:52,149] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:06:52,553] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:06:52,565] {logging_mixin.py:115} INFO - [2025-09-06 13:06:52,565] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:06:52,585] {logging_mixin.py:115} INFO - [2025-09-06 13:06:52,584] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:06:52,607] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.464 seconds
[2025-09-06 13:07:26,964] {processor.py:153} INFO - Started process (PID=37465) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:07:26,965] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:07:26,966] {logging_mixin.py:115} INFO - [2025-09-06 13:07:26,966] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:07:27,374] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:07:27,387] {logging_mixin.py:115} INFO - [2025-09-06 13:07:27,387] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:07:27,406] {logging_mixin.py:115} INFO - [2025-09-06 13:07:27,405] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:07:27,428] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.471 seconds
[2025-09-06 13:07:58,325] {processor.py:153} INFO - Started process (PID=37542) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:07:58,326] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:07:58,327] {logging_mixin.py:115} INFO - [2025-09-06 13:07:58,327] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:07:58,733] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:07:58,746] {logging_mixin.py:115} INFO - [2025-09-06 13:07:58,746] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:07:58,765] {logging_mixin.py:115} INFO - [2025-09-06 13:07:58,765] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:07:58,787] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.466 seconds
[2025-09-06 13:08:29,970] {processor.py:153} INFO - Started process (PID=37618) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:08:29,970] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:08:29,971] {logging_mixin.py:115} INFO - [2025-09-06 13:08:29,971] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:08:30,375] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:08:30,388] {logging_mixin.py:115} INFO - [2025-09-06 13:08:30,388] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:08:30,407] {logging_mixin.py:115} INFO - [2025-09-06 13:08:30,407] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:08:30,429] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.463 seconds
[2025-09-06 13:09:06,712] {processor.py:153} INFO - Started process (PID=37702) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:09:06,715] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:09:06,716] {logging_mixin.py:115} INFO - [2025-09-06 13:09:06,716] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:09:07,127] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:09:07,141] {logging_mixin.py:115} INFO - [2025-09-06 13:09:07,141] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:09:07,169] {logging_mixin.py:115} INFO - [2025-09-06 13:09:07,169] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:09:07,192] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.493 seconds
[2025-09-06 13:09:43,963] {processor.py:153} INFO - Started process (PID=37797) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:09:43,965] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:09:43,966] {logging_mixin.py:115} INFO - [2025-09-06 13:09:43,966] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:09:44,380] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:09:44,392] {logging_mixin.py:115} INFO - [2025-09-06 13:09:44,392] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:09:44,411] {logging_mixin.py:115} INFO - [2025-09-06 13:09:44,411] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:09:44,434] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.476 seconds
[2025-09-06 13:10:15,747] {processor.py:153} INFO - Started process (PID=37874) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:10:15,749] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:10:15,750] {logging_mixin.py:115} INFO - [2025-09-06 13:10:15,749] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:10:16,326] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:10:16,341] {logging_mixin.py:115} INFO - [2025-09-06 13:10:16,340] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:10:16,364] {logging_mixin.py:115} INFO - [2025-09-06 13:10:16,363] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:10:16,389] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.650 seconds
[2025-09-06 13:10:53,057] {processor.py:153} INFO - Started process (PID=37965) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:10:53,059] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:10:53,060] {logging_mixin.py:115} INFO - [2025-09-06 13:10:53,060] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:10:53,509] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:10:53,522] {logging_mixin.py:115} INFO - [2025-09-06 13:10:53,521] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:10:53,542] {logging_mixin.py:115} INFO - [2025-09-06 13:10:53,542] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:10:53,564] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.519 seconds
[2025-09-06 13:11:24,147] {processor.py:153} INFO - Started process (PID=38036) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:11:24,148] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:11:24,150] {logging_mixin.py:115} INFO - [2025-09-06 13:11:24,149] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:11:24,568] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:11:24,581] {logging_mixin.py:115} INFO - [2025-09-06 13:11:24,581] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:11:24,600] {logging_mixin.py:115} INFO - [2025-09-06 13:11:24,600] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:11:24,624] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.489 seconds
[2025-09-06 13:11:56,695] {processor.py:153} INFO - Started process (PID=38139) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:11:56,696] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:11:56,699] {logging_mixin.py:115} INFO - [2025-09-06 13:11:56,698] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:12:00,998] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:12:01,014] {logging_mixin.py:115} INFO - [2025-09-06 13:12:01,014] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:12:01,047] {logging_mixin.py:115} INFO - [2025-09-06 13:12:01,047] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:12:01,083] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 4.422 seconds
[2025-09-06 13:12:38,975] {processor.py:153} INFO - Started process (PID=38259) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:12:38,976] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:12:38,977] {logging_mixin.py:115} INFO - [2025-09-06 13:12:38,977] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:12:39,506] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:12:39,518] {logging_mixin.py:115} INFO - [2025-09-06 13:12:39,518] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:12:39,538] {logging_mixin.py:115} INFO - [2025-09-06 13:12:39,537] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:12:39,560] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.589 seconds
[2025-09-06 13:13:11,577] {processor.py:153} INFO - Started process (PID=38341) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:13:11,578] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:13:11,579] {logging_mixin.py:115} INFO - [2025-09-06 13:13:11,578] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:13:12,038] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:13:12,050] {logging_mixin.py:115} INFO - [2025-09-06 13:13:12,050] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:13:12,069] {logging_mixin.py:115} INFO - [2025-09-06 13:13:12,069] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:13:12,091] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.519 seconds
[2025-09-06 13:13:44,155] {processor.py:153} INFO - Started process (PID=38416) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:13:44,157] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:13:44,158] {logging_mixin.py:115} INFO - [2025-09-06 13:13:44,157] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:13:44,614] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:13:44,627] {logging_mixin.py:115} INFO - [2025-09-06 13:13:44,627] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:13:44,646] {logging_mixin.py:115} INFO - [2025-09-06 13:13:44,646] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:13:44,672] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.523 seconds
[2025-09-06 13:14:16,664] {processor.py:153} INFO - Started process (PID=38501) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:14:16,666] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:14:16,667] {logging_mixin.py:115} INFO - [2025-09-06 13:14:16,667] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:14:17,224] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:14:17,242] {logging_mixin.py:115} INFO - [2025-09-06 13:14:17,242] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:14:17,268] {logging_mixin.py:115} INFO - [2025-09-06 13:14:17,268] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:14:17,296] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.642 seconds
[2025-09-06 13:14:49,001] {processor.py:153} INFO - Started process (PID=38581) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:14:49,004] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:14:49,008] {logging_mixin.py:115} INFO - [2025-09-06 13:14:49,007] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:14:49,928] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:14:49,959] {logging_mixin.py:115} INFO - [2025-09-06 13:14:49,958] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:14:50,004] {logging_mixin.py:115} INFO - [2025-09-06 13:14:50,004] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:14:50,059] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 1.078 seconds
[2025-09-06 13:15:30,531] {processor.py:153} INFO - Started process (PID=38671) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:15:30,535] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:15:30,539] {logging_mixin.py:115} INFO - [2025-09-06 13:15:30,538] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:15:34,464] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:15:34,481] {logging_mixin.py:115} INFO - [2025-09-06 13:15:34,481] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:15:34,506] {logging_mixin.py:115} INFO - [2025-09-06 13:15:34,506] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:15:34,529] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 4.011 seconds
[2025-09-06 13:16:07,326] {processor.py:153} INFO - Started process (PID=38743) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:16:07,327] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:16:07,328] {logging_mixin.py:115} INFO - [2025-09-06 13:16:07,328] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:16:07,854] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:16:07,868] {logging_mixin.py:115} INFO - [2025-09-06 13:16:07,868] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:16:07,890] {logging_mixin.py:115} INFO - [2025-09-06 13:16:07,890] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:16:07,913] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.594 seconds
[2025-09-06 13:16:38,293] {processor.py:153} INFO - Started process (PID=38875) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:16:38,299] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:16:38,305] {logging_mixin.py:115} INFO - [2025-09-06 13:16:38,305] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:16:40,448] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:16:40,462] {logging_mixin.py:115} INFO - [2025-09-06 13:16:40,462] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:16:40,497] {logging_mixin.py:115} INFO - [2025-09-06 13:16:40,497] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:16:40,520] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 2.243 seconds
[2025-09-06 13:17:18,088] {processor.py:153} INFO - Started process (PID=39310) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:17:18,089] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:17:18,090] {logging_mixin.py:115} INFO - [2025-09-06 13:17:18,090] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:17:18,637] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:17:18,657] {logging_mixin.py:115} INFO - [2025-09-06 13:17:18,657] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:17:18,683] {logging_mixin.py:115} INFO - [2025-09-06 13:17:18,683] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:17:18,711] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.627 seconds
[2025-09-06 13:17:52,169] {processor.py:153} INFO - Started process (PID=39493) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:17:52,170] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:17:52,173] {logging_mixin.py:115} INFO - [2025-09-06 13:17:52,172] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:17:53,044] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:17:53,061] {logging_mixin.py:115} INFO - [2025-09-06 13:17:53,061] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:17:53,083] {logging_mixin.py:115} INFO - [2025-09-06 13:17:53,082] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:17:53,105] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.946 seconds
[2025-09-06 13:18:31,381] {processor.py:153} INFO - Started process (PID=39587) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:18:31,383] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:18:31,384] {logging_mixin.py:115} INFO - [2025-09-06 13:18:31,383] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:18:33,037] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:18:33,070] {logging_mixin.py:115} INFO - [2025-09-06 13:18:33,069] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:18:33,099] {logging_mixin.py:115} INFO - [2025-09-06 13:18:33,098] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:18:33,120] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 1.746 seconds
[2025-09-06 13:19:03,393] {processor.py:153} INFO - Started process (PID=39679) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:19:03,395] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:19:03,396] {logging_mixin.py:115} INFO - [2025-09-06 13:19:03,396] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:19:04,410] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:19:04,431] {logging_mixin.py:115} INFO - [2025-09-06 13:19:04,430] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:19:04,453] {logging_mixin.py:115} INFO - [2025-09-06 13:19:04,453] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:19:04,480] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 1.091 seconds
[2025-09-06 13:19:41,940] {processor.py:153} INFO - Started process (PID=39767) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:19:41,942] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:19:41,943] {logging_mixin.py:115} INFO - [2025-09-06 13:19:41,942] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:19:42,404] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:19:42,417] {logging_mixin.py:115} INFO - [2025-09-06 13:19:42,417] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:19:42,436] {logging_mixin.py:115} INFO - [2025-09-06 13:19:42,436] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:19:42,458] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.528 seconds
[2025-09-06 13:20:15,692] {processor.py:153} INFO - Started process (PID=39926) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:20:15,695] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:20:15,697] {logging_mixin.py:115} INFO - [2025-09-06 13:20:15,697] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:20:16,161] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:20:16,173] {logging_mixin.py:115} INFO - [2025-09-06 13:20:16,173] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:20:16,193] {logging_mixin.py:115} INFO - [2025-09-06 13:20:16,193] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:20:16,214] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.535 seconds
[2025-09-06 13:20:49,315] {processor.py:153} INFO - Started process (PID=40067) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:20:49,316] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:20:49,317] {logging_mixin.py:115} INFO - [2025-09-06 13:20:49,317] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:20:49,773] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:20:49,786] {logging_mixin.py:115} INFO - [2025-09-06 13:20:49,786] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:20:49,805] {logging_mixin.py:115} INFO - [2025-09-06 13:20:49,805] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:20:49,827] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.516 seconds
[2025-09-06 13:21:24,173] {processor.py:153} INFO - Started process (PID=40155) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:21:24,174] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:21:24,175] {logging_mixin.py:115} INFO - [2025-09-06 13:21:24,175] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:21:24,708] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:21:24,721] {logging_mixin.py:115} INFO - [2025-09-06 13:21:24,721] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:21:24,740] {logging_mixin.py:115} INFO - [2025-09-06 13:21:24,740] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:21:24,762] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.595 seconds
[2025-09-06 13:21:55,665] {processor.py:153} INFO - Started process (PID=40262) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:21:55,666] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:21:55,667] {logging_mixin.py:115} INFO - [2025-09-06 13:21:55,667] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:21:57,139] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:21:57,155] {logging_mixin.py:115} INFO - [2025-09-06 13:21:57,155] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:21:57,175] {logging_mixin.py:115} INFO - [2025-09-06 13:21:57,175] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:21:57,197] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 1.541 seconds
[2025-09-06 13:22:29,928] {processor.py:153} INFO - Started process (PID=40384) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:22:29,930] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:22:29,931] {logging_mixin.py:115} INFO - [2025-09-06 13:22:29,931] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:22:30,715] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:22:30,732] {logging_mixin.py:115} INFO - [2025-09-06 13:22:30,731] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:22:30,760] {logging_mixin.py:115} INFO - [2025-09-06 13:22:30,760] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:22:30,787] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.868 seconds
[2025-09-06 13:23:07,067] {processor.py:153} INFO - Started process (PID=40503) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:23:07,068] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:23:07,070] {logging_mixin.py:115} INFO - [2025-09-06 13:23:07,069] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:23:07,544] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:23:07,558] {logging_mixin.py:115} INFO - [2025-09-06 13:23:07,558] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:23:07,580] {logging_mixin.py:115} INFO - [2025-09-06 13:23:07,580] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:23:07,606] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.544 seconds
[2025-09-06 13:23:38,861] {processor.py:153} INFO - Started process (PID=40606) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:23:38,864] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:23:38,868] {logging_mixin.py:115} INFO - [2025-09-06 13:23:38,867] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:23:39,505] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:23:39,519] {logging_mixin.py:115} INFO - [2025-09-06 13:23:39,519] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:23:39,540] {logging_mixin.py:115} INFO - [2025-09-06 13:23:39,540] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:23:39,562] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.721 seconds
[2025-09-06 13:24:16,273] {processor.py:153} INFO - Started process (PID=40776) to work on /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:24:16,274] {processor.py:641} INFO - Processing file /home/lucas/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2025-09-06 13:24:16,275] {logging_mixin.py:115} INFO - [2025-09-06 13:24:16,275] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:24:16,761] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climatico']) retrieved from /home/lucas/Documents/airflowalura/dags/dados_climaticos.py
[2025-09-06 13:24:16,774] {logging_mixin.py:115} INFO - [2025-09-06 13:24:16,774] {dag.py:2379} INFO - Sync 1 DAGs
[2025-09-06 13:24:16,793] {logging_mixin.py:115} INFO - [2025-09-06 13:24:16,793] {dag.py:2927} INFO - Setting next_dagrun for dados_climatico to 2025-09-01T00:00:00+00:00, run_after=2025-09-08T00:00:00+00:00
[2025-09-06 13:24:16,816] {processor.py:161} INFO - Processing /home/lucas/Documents/airflowalura/dags/dados_climaticos.py took 0.548 seconds
